---
version: 0.2

env:
  variables:
    s3_bucket: mickey8-sonarqube
    home_dir: $CODEBUILD_SRC_DIR/codebuild
    src_dir: $home_dir/src
    target_dir: $home_dir/target
    #sonarqube_version: 7.7
    #manual_plugins:
    #manual_plugins_xxx:
#

phases:
  install:
    commands:
      - pip3 install jinja2
  pre_build:
    commands:
      - mkdir $target_dir
  build:
    commands:
      - cd $target_dir
      - curl -O https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-${sonarqube_version}.zip
      - python3 $home_dir/render_template.py
      - cp -r $src_dir/* $target_dir
      - aws deploy push --application-name sonarqube --s3-location s3://${s3_bucket}/sonarqube/sonarqube.zip
